{% set version = "0.7-6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rpostgresql
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RPostgreSQL_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RPostgreSQL/RPostgreSQL_{{ version }}.tar.gz
  sha256: 385939708b6a3657663409f91e165ded0ff5268d1dc6225e0f9b34764baf2d2c

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dbi >=0.3
    - libpq                      # [linux]
  run:
    - r-base
    - r-dbi >=0.3
    - libpq

test:
  commands:
    - $R -e "library('RPostgreSQL')"           # [not win]
    - "\"%R%\" -e \"library('RPostgreSQL')\""  # [win]

about:
  home: https://github.com/tomoakin/RPostgreSQL, https://cran.r-project.org/package=DBI, http://www.postgresql.org
  license: GPL-3.0-only
  license_family: GPL3
  summary: Database interface and 'PostgreSQL' driver for 'R'. This package provides a Database Interface 'DBI' compliant  driver for 'R' to access 'PostgreSQL' database systems.   In order to build and install this package from source, 'PostgreSQL'  itself must be present your system to provide 'PostgreSQL' functionality  via
    its libraries and header files. These files are provided as 'postgresql-devel' package under some Linux distributions. On 'macOS' and 'Microsoft Windows' system the attached 'libpq' library source will be used.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - mariusvniekerk
