appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: L0nzv7tWRkZ4c0FpeG5yvBK8CQAZIeXiYZOs0REBi0k9ffXj5XhD1145QG1hlOu0E+0kAp1qX3UXdbvFkpPY7DA0NTaIYo5EVGjmoDMYluprBL2D52eOZ0uUoZJuAJgiLPXwjoGtTKtpk7UHpm+s4sfV2gvbnQHBB+yMASuIjCxFUzbym40ttV/gaZX2ZFZZV1eiXDPMnlu+FdqNrYNPrYBH/IQ4mR75385uD0V9eEOUxmIcQuLBmHh8avkkeI2Ywh3hTDDTTU4PNOlNu3fFH10Jm1DngJO5iyVsG0JS39iOxH9X+OPQFJ9xJWgoGMSmIXTXlSdw0Cit9bsFKTZSeoLVZ4j+lErun5/Qak5ylp4LJp4rGqcq1k0Ywaew8U+gH1Z3XBeTQuGUwrhq4vo1WKGPjyyO3KeVp2DLTZ0YNTZcuzkWQU8Na+89PQicrhuW35GrJZ+3D1xtd8Aw2qw4DMOQwLgZ0Q8haED/2AYUBpwMdO4bupR0/dffaTXvtV2u/YnZtVkZdtpRJvmNVd+wNzSiBmcxx+SXAeulNsCG3wuYkviE8s7BIsgXtbvtACs92Gpf9E+YXJnyprEx5ZOzg3TaNhalS++OvpNCaqZk6PfRWbHO4tfLU0NzgwQDBWceuWOPaYvGrletaZM0U8NIsY/pAfHijhTlpJC+cUBOsSI=}
